### ISSUE TITLE
ROI drawer gives error during trace extraction, then crashes

### ISSUE THREAD

**Issue by samupicard** [yves-weissenberger/Multiphoton-Toolbox#8]
Traceback (most recent call last):                                                                                        
File "Documents\twoptb\ROIs\PyQtGraph_ROI_Drawer.py", line 572, in buttonClicked                                          self._extract_trace(i)                                                                                                
File "Documents\twoptb\ROIs\PyQtGraph_ROI_Drawer.py", line 597, in _extract_trace                                         temp = areaFile[:,yLims[0]:yLims[1],xLims[0]:xLims[1]] *self.ROI_attrs['masks'][idx]                                  
File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1474482483473\work\h5py\_objects.c:2705)                                                                                                       File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1474482483473\work\h5py\_objects.c:2663)                                                                                                       File "C:\Users\mert3628\Anaconda2\lib\site-packages\h5py\_hl\dataset.py", line 462, in __getitem__                        selection = sel.select(self.shape, args, dsid=self.id)                                                                
File "C:\Users\mert3628\Anaconda2\lib\site-packages\h5py\_hl\selections.py", line 92, in select                           sel[args]                                                                                                             
File "C:\Users\mert3628\Anaconda2\lib\site-packages\h5py\_hl\selections.py", line 259, in __getitem__                     start, count, step, scalar = _handle_simple(self.shape,args)                                                          
File "C:\Users\mert3628\Anaconda2\lib\site-packages\h5py\_hl\selections.py", line 443, in _handle_simple                  x,y,z = _translate_slice(arg, length)                                                                                 
File "C:\Users\mert3628\Anaconda2\lib\site-packages\h5py\_hl\selections.py", line 484, in _translate_slice                raise ValueError("Reverse-order selections are not allowed")                                                        
ValueError: Reverse-order selections are not allowed

**Comment by yves-weissenberger** [comment]
problem was caused by ROIs being drawn out of bounds. This option has been disabled now
